# cloudflare/cdn-worker/wrangler.toml
name = 'kickdashboard'
main = "src/index.ts"
compatibility_date = "2025-12-01"

[vars]
# Must match the custom domain you mapped in R2 Custom Domains
PUBLIC_HOST = "cdn.kickdashboard.com"

[[r2_buckets]]
binding = "MEDIA_BUCKET"
bucket_name = "sweetflips-media"

[observability]
[observability.logs]
enabled = false
head_sampling_rate = 1
invocation_logs = true
persist = true
